---

project_dir: ~/.script
downloads_dir: ~/Downloads

downloads: ~/.ansible-downloads/

# Options
configure_dotfiles: yes
configure_sudoers: yes
configure_osx: no
configure_extra: yes
configure_dock: yes

# dotfiles options
dotfiles_repo: https://github.com/z0ph/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/.dotfiles
dotfiles_files:
  - .gitignore
  - .osx
  - .zshrc
  - .alias.sh
  - .bashrc

homebrew_taps:
  - homebrew/cask
  - wallix/awless
  - caskroom/fonts
  - homebrew/cask-versions

homebrew_installed_packages:
  - autoconf
  - automake
  - awless # brew tap wallix/awless; brew install awless
  - aws-shell
  - awscli
  - bash-completion
  - calc
  - coreutils
  - curl
  - direnv
  - dockutil
  - git
  - gnupg
  - gnutls
  - go
  - gpg
  - htop
  - kubernetes-cli
  - kubernetes-helm
  - lftp
  - libgcrypt
  - mas
  - ncdu
  - nmap
  - node
  - nvm
  - openssl
  - packer
  - python
  - python3
  - ruby
  - sqlite
  - ssh-copy-id
  - terraform
  - terminal-notifier
  - tldr
  - tree
  - unrar
  - vim
  - watch
  - wget
  - zsh

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - alfred
  - cleanmymac
  - cyberduck # ftp client
  - docker
  - dropbox
  - enpass # password manager
  - etcher # flash usb drives
  - firefox
  - font-fira-mono-for-powerline 
  - font-source-code-pro # font for zsh
  - franz # client whatsapp, telegram, slack, etc.
  - gitkraken # git with a gui
  - google-chrome
  - grammarly
  - handbrake
  - iterm2 # terminal emulator
  - istat-menus5 # force version 5
  - licecap # capture as a gif
  - mark-text # Markdown editor
  - pycharm
  - sequel-pro # MySQL Client (GUI)
  - spotify
  - sublime-text
  - slack
  - skype
  - teamviewer
  - transmission # torrent client
  - transmit # sftp client
  - tunnelblick # vpn client
  - visual-studio-code
  - vlc

# See `geerlingguy.mas` role documentation for usage instructions.
mas_signin_dialog: yes
mas_installed_apps:
  - { id: 441258766, name: "Magnet" } # Windows Management
  - { id: 1176895641, name: "Spark" } # Email Client
  - { id: 1039633667, name: "Irvue" } # Awesome wallpapers
  - { id: 409183694, name: "Keynote" }
  - { id: 557168941, name: "Tweetbot for Twitter" }
  - { id: 1295203466, name: "Microsoft Remote Desktop" } # RDP Client
  - { id: 784801555, name: "Microsoft OneNote" }

mas_upgrade_all_apps: yes

osx_script: "~/.osx --no-restart"

# Dock
dockitems_disabled:
  - Launchpad
  - Siri
  - Mail
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - Calendar
  - Terminal
  - Pages
  - Numbers
  - Keynote

dockitems_enabled:
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 1
  - name: Firefox
    path: "/Applications/Firefox.app"
    pos: 2
  - name: Tweetbot
    path: "/Applications/Tweetbot.app"
    pos: 3
  - name: Spark
    path: "/Applications/Spark.app"
    pos: 4
  - name: Slack
    path: "/Applications/Slack.app"
    pos: 5
  - name: iTerm
    path: "/Applications/iTerm.app"
    pos: 6
  - name: Sublime Text
    path: "/Applications/Sublime Text.app"
    pos: 7
  - name: Microsoft OneNote
    path: "/Applications/Microsoft OneNote.app"
    pos: 8
  - name: System Preferences
    path: "/Applications/System Preferences.app"
    pos: 9
  - name: Image Capture
    path: "/Applications/Image Capture.app"
    pos: 10
  - name: Spotify
    path: "/Applications/Spotify.app"
    pos: 11
  - name: Calculator
    path: "/Applications/Calculator.app"
    pos: 12
  - name: Dictionary
    path: "/Applications/Dictionary.app"
    pos: 13
  - name: Franz
    path: "/Applications/Franz.app"
    pos: 14
  - name: Enpass
    path: "/Applications/Enpass.app"
    pos: 15
  - name: Skype
    path: "/Applications/Skype.app"
    pos: 16